version: '3.8'

services:
  # 1. Kontainer Aplikasi Hybrid (Web + CLI Terminal)
  todo-app:
    build: .
    container_name: running-todo-compose
    stdin_open: true  
    tty: true         
    ports:
      - "${APP_PORT}:${APP_PORT}" # Membaca port dinamis dari file .env
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}

  # 2. Kontainer Database PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: postgres-todo-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: